services:
  db:
    image: mariadb:latest            # Usando MariaDB ao invés de PostgreSQL
    restart: always
    container_name: trashmap-database
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD}  # importante para root
    ports:
      - "3306:3306"                   # MariaDB padrão
    networks:
      private_network:
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  backend:
    build:
      context: "../backend"
    container_name: trashmap-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://${MARIADB_HOST}:${MARIADB_PORT}/${MARIADB_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MARIADB_USER}
      SPRING_DATASOURCE_PASSWORD: ${MARIADB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: mariadb
      MARIADB_HOST: db
      MARIADB_PORT: 3306
    depends_on:
      db:
        condition: service_healthy
    networks:
      private_network:
      public_network:

  frontend:
    build:
      context: "../frontend"
    container_name: trashmap-frontend
    restart: always
    ports:
      - "80:80"
    networks:
      public_network:

networks:
  private_network:
    driver: bridge
  public_network:
    driver: bridge
