spring.application.name=TrashMap
server.port=8080
spring.jpa.show-sql=true
spring.profiles.active=mariadb


# Segredo para assinar o token (use uma string longa e aleatória)
api.security.token.secret=123456789012345678901234567890_UmaSenhaBemDificil_TrashMap

# Expiração do token em milissegundos (ex: 2 horas = 7200000)
api.security.token.expiration=7200000