spring.application.name=TrashMap
server.port=8080
spring.jpa.show-sql=true
spring.profiles.active=h2
jwt.secret=1b7BvP3kE7Y8Xg2DnH3aQ0uR4sT5wF6zJ9hL4mI1oK8qV7pC5rS0tU3yX6vW9aZ2eY5d
jwt.expiration=86400000
logging.level.org.apache.coyote.http11.Http11Processor=INFO



