version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: trashmap
      POSTGRES_USER: natan
      POSTGRES_PASSWORD: natan
    ports:
      - "5432:5432"
    networks:
      - private_network

  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/trashmap
      SPRING_DATASOURCE_USERNAME: trasmap_user
      SPRING_DATASOURCE_PASSWORD: dOntSt0ptry*
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: postgres
    networks:
      - private_network
      - public_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    networks:
      - public_network

networks:
  private_network:
    driver: bridge
  public_network:
    driver: bridge
